import pandas as pd
import pyautogui as pa
import time
pa.PAUSE = 1.5
pa.press('win')
pa.write('chrome')
pa.press('enter')
time.sleep(4)
pa.write('https://dlp.hashtagtreinamentos.com/python/intensivao/login')
pa.press('enter')
time.sleep(3)
pa.press('tab')
pa.write('henriquegarcia2108@gmail.com')
pa.press('tab')
pa.write('12345678')
pa.press('enter')
time.sleep(2)
tabela = pd.read_csv('produtos.csv')
for linha in tabela.index:
    codigo_produto = str(tabela.loc[linha, 'codigo'])
    pa.click(x=573, y=242)
    pa.write(codigo_produto)
    pa.press('tab')
    marca_produto = str(tabela.loc[linha, 'marca'])
    pa.write(marca_produto)
    pa.press('tab')
    tipo_produto = str(tabela.loc[linha, 'tipo'])
    pa.write(tipo_produto)
    pa.press('tab')
    categoria_produto = str(tabela.loc[linha, 'categoria'])
    pa.write(categoria_produto)
    pa.press('tab')
    preco_produto = str(tabela.loc[linha, 'preco_unitario'])
    pa.write(preco_produto)
    pa.press('tab')
    custo_produto = str(tabela.loc[linha, 'custo'])
    pa.write(custo_produto)
    pa.press('tab')
    obs_produto = str(tabela.loc[linha, 'obs'])
    if obs_produto != 'nan':
        pa.write(obs_produto)
    pa.press('enter')
    pa.scroll(500)

